---
apiVersion: v2
name: k8s-ldap-auth
version: 0.1.3
description: Kubernetes webhook token authentication plugin implementation using ldap.
keywords:
  - kubernetes
  - ldap
  - authentication
  - k8s
  - kubernetes-webhook
home: https://github.com/vbouchaud/k8s-ldap-auth
maintainers:
  - name: Vianney Bouchaud
    url: https://vianney.bouchaud.org
type: application
appVersion: "v4.0.0"
